# Generated by Django 5.1.4 on 2025-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True, verbose_name='Наименование клиента')),
                ('legal_address', models.CharField(default=None, max_length=50, null=True, verbose_name='Юридический адрес')),
                ('actual_address', models.CharField(default=None, max_length=50, null=True, verbose_name='Фактический адрес')),
                ('inn', models.CharField(default='', max_length=12, null=True, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(default=None, max_length=9, null=True, verbose_name='КПП')),
                ('ogrn', models.CharField(default=None, max_length=15, null=True, verbose_name='ОГРН')),
            ],
        ),
    ]
