# Generated by Django 5.1.4 on 2025-01-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='actual_address',
            field=models.CharField(max_length=50, verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='inn',
            field=models.CharField(max_length=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='kpp',
            field=models.CharField(max_length=9, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='legal_address',
            field=models.CharField(max_length=50, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование клиента'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ogrn',
            field=models.CharField(max_length=13, verbose_name='ОГРН'),
        ),
    ]
