# Generated by Django 5.1.4 on 2025-01-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='body',
        ),
    ]
