# Generated by Django 5.1.4 on 2025-01-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_template_alter_participant_inn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
