# Generated by Django 5.1.4 on 2025-08-27 14:47

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование шаблона')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Тело шаблона')),
                ('category', models.CharField(choices=[('sales', 'Договор купли-продажи'), ('rent', 'Договор аренды')], max_length=10)),
            ],
        ),
    ]
