# Generated by Django 5.1.4 on 2025-01-10 13:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='content',
            field=ckeditor.fields.RichTextField(default=123),
            preserve_default=False,
        ),
    ]
