# Generated by Django 5.1.4 on 2025-01-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('sales', 'Договор купли продажи'), ('rent', 'Договор аренды')], default='sales', max_length=10),
        ),
    ]
