# Generated by Django 5.1.4 on 2025-01-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_template_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='content',
        ),
    ]
