# Generated by Django 5.1.4 on 2025-01-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_template_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('sales', 'Договор купли продажи'), ('rent', 'Договор аренды')], max_length=10),
        ),
    ]
