# Generated by Django 5.1.4 on 2025-01-10 14:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_remove_template_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Тело шаблона'),
        ),
    ]
