# Generated by Django 5.1.4 on 2025-01-10 14:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_alter_template_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='body',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Тело шаблона'),
        ),
    ]
